function cfg = tw1_minpa_quality_flag_config()
%TW1_MINPA_QUALITY_FLAG_CONFIG Approved MINPA H+/O+/O2+ flag definition.

cfg.algorithm_version = '2026-07-13-seven-band-all-species-v2-mode12-product-time';
cfg.species = {'H', 'O', 'O2'};
cfg.species_labels = {'H+', 'O+', 'O2+'};
cfg.flag_bits = struct( ...
    'sparse_caution', uint32(1), ...
    'sparse_invalid', uint32(2), ...
    'uv_contamination', uint32(4), ...
    'evenodd_error', uint32(8), ...
    'high_channel', uint32(16));

cfg.thresholds = struct();
cfg.thresholds.valid_raw_channel_min = 0;
cfg.thresholds.valid_raw_channel_max_exclusive = 1e8;
cfg.thresholds.sparse_invalid_lt = 5;
cfg.thresholds.sparse_caution_min = 5;
cfg.thresholds.sparse_caution_max = 10;
cfg.thresholds.uv_def_threshold = 1e5;
cfg.thresholds.uv_fraction_threshold = 0.8;
cfg.thresholds.alternating_peak_def_min = 1e5;
cfg.thresholds.alternating_valley_neighbor_fraction_max = 0.5;
cfg.thresholds.alternating_extrema_fraction_threshold = 0.525;
cfg.thresholds.alternating_phase_fraction_threshold = 0.55;
cfg.thresholds.alternating_energy_bands_eV = [ ...
    0, Inf; ...
    0, 30; ...
    30, 300; ...
    300, Inf; ...
    0, 50; ...
    50, 500; ...
    500, 5000];
cfg.thresholds.alternating_energy_band_labels = { ...
    'all_energy', '0_30eV', '30_300eV', '300_maxeV', ...
    '0_50eV', '50_500eV', '500_5000eV'};
cfg.thresholds.high_channel_def_threshold = 1e10;

cfg.time_match_tolerance_s = 1e-3;
cfg.missing_binary = '99999';
cfg.binary_bit_order = 'problem bits 1,2,3,4,5';
end
